function printCompareSummary(comparison)
% printCompareSummary  打印对比结果摘要

    fprintf('\n========== 算法对比结果 ==========\n');
    fprintf('指标                      老算法        新算法\n');
    fprintf('------------------------------------------------------------------\n');
    fprintf('最终覆盖率               %.3f         %.3f\n', ...
        comparison.finalCovOld, comparison.finalCovNew);
    fprintf('海面覆盖率               %.3f         %.3f\n', ...
        comparison.finalSeaOld, comparison.finalSeaNew);
    fprintf('岛屿覆盖率               %.3f         %.3f\n', ...
        comparison.finalIslandOld, comparison.finalIslandNew);
    fprintf('总仿真步数               %d            %d\n', ...
        comparison.stopStepOld, comparison.stopStepNew);

    if isfield(comparison, 'eta_B_Old')
        fprintf('------------------------------------------------------------------\n');
        fprintf('--- 通信对比 ---\n');
        fprintf('基本服务率 eta_B         %.3f         %.3f\n', ...
            comparison.eta_B_Old, comparison.eta_B_New);
        fprintf('LoS服务率 eta_L          %.3f         %.3f\n', ...
            comparison.eta_L_Old, comparison.eta_L_New);
        fprintf('平均LoS链路比            %.3f         %.3f\n', ...
            comparison.rho_LoS_Old, comparison.rho_LoS_New);
        fprintf('平均SINR (dB)            %.1f         %.1f\n', ...
            comparison.gamma_bar_Old, comparison.gamma_bar_New);
        fprintf('平均数据率 (kbps)        %.1f         %.1f\n', ...
            comparison.R_bar_Old, comparison.R_bar_New);
        fprintf('最大断连时长 (步)        %.0f           %.0f\n', ...
            comparison.tau_out_Old, comparison.tau_out_New);
        fprintf('G^B代数连通度            %.4f         %.4f\n', ...
            comparison.lambda2_B_Old, comparison.lambda2_B_New);
        fprintf('G^L代数连通度            %.4f         %.4f\n', ...
            comparison.lambda2_L_Old, comparison.lambda2_L_New);
    end
    fprintf('====================================\n');
end
